# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtDyCVFE4m4ZLIhFX76RATOwO7CXovfS
"""

import pandas as pd

"""#Creating data frames"""

df = pd.read_csv("BigBasket.csv")

df

df['Price'].mean()

df['Price'].mode()

df['Price'].median()

df['Price']=df['Price'].fillna(df['Price'].mean())

df['Price']=df['Price'].fillna(df['Price'].median())

df['Price']=df['Price'].fillna(df['Price'].mode())

df.info()

df.describe()

df.dtypes

df.isnull()

df.notnull()

df.drop_duplicates()

df.nunique()

df['Category'].value_counts()

df.groupby('Category')

df.plot(kind='line')

df.plot(kind='bar')

df.plot(kind='barh')

df.plot(kind='hist')

df.plot(kind='box')

df.plot(kind='kde')

df.plot(kind='pie', y = 'Price')

